/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.basic.business.view;

import com.basic.business.controller.DestinationController;
import com.basic.business.entities.Destinations;
import com.basic.business.system.IDestinationService;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import org.springframework.boot.autoconfigure.kafka.ConcurrentKafkaListenerContainerFactoryConfigurer;
import org.springframework.stereotype.Component;
import javax.swing.GroupLayout.Alignment;
import javax.swing.RowFilter;
import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;

/**
 *
 * @author ecem
 */
@Component
public class MainView extends javax.swing.JFrame {
	public IDestinationService destinationService;

	/**
	 * Creates new form view
	 */
	public MainView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jPanelMain = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblDestinations = new javax.swing.JTable();
		lblSearch = new javax.swing.JLabel();
		txtSearch = new javax.swing.JTextField();
		btnDetails = new javax.swing.JButton();
		JLabel lblSuccess = new JLabel("Items deleted successfully.");
		lblSuccess.setForeground(Color.GREEN);
		lblSuccess.setVisible(false);
		btnDetails.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent details) {
				int selectedID;
				if ((selectedID=tblDestinations.getSelectedRow()) != -1) {
					java.awt.Window win[] = java.awt.Window.getWindows();
					for (int i = 0; i < win.length; i++) {
						win[i].dispose();
					}
					int id=destinationService.getAll().get(selectedID).getId();
					DetailsView detailsView = new DetailsView(destinationService, id);
					detailsView.setVisible(true);
				}
			}
		});
		btnDelete = new javax.swing.JButton();
		btnDelete.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				int[] selectedItems=tblDestinations.getSelectedRows();
				Destinations[] destinations=new Destinations[tblDestinations.getSelectedRowCount()];
				int j=0;
				for(int i:selectedItems) {
					destinations[j]=destinationService.getAll().get(i);
					j++;
				}
				for(Destinations destination:destinations) {
					destinationService.delete(destination);					
				}
				fillTable(destinationService);
				lblSuccess.setVisible(true);
				
			}
		});
		btnAdd = new javax.swing.JButton();

		btnAdd.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				java.awt.Window win[] = java.awt.Window.getWindows();
				for (int i = 0; i < win.length; i++) {
					win[i].dispose();
				}
				AddView addView = new AddView();
				addView.setVisible(true);
				addView.setManager(destinationService);
			}
		});

		jButton1.setText("jButton1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		tblDestinations.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Name", "Country", "City" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tblDestinations);

		lblSearch.setText("Search : ");

		txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				txtSearchKeyReleased(evt);
			}
		});

		btnDetails.setText("Details");

		btnDelete.setText("Delete");

		btnAdd.setText("Add");
		
		

		javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
		jPanelMainLayout.setHorizontalGroup(
			jPanelMainLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanelMainLayout.createSequentialGroup()
					.addGap(82)
					.addGroup(jPanelMainLayout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 550, GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanelMainLayout.createSequentialGroup()
							.addComponent(lblSearch)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(txtSearch, GroupLayout.PREFERRED_SIZE, 503, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanelMainLayout.createSequentialGroup()
							.addComponent(btnDetails, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnAdd, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnDelete, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(lblSuccess)))
					.addContainerGap(108, Short.MAX_VALUE))
		);
		jPanelMainLayout.setVerticalGroup(
			jPanelMainLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanelMainLayout.createSequentialGroup()
					.addGap(18)
					.addGroup(jPanelMainLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblSearch)
						.addComponent(txtSearch, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
					.addGap(16)
					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addGroup(jPanelMainLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnDetails, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnAdd, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnDelete, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblSuccess))
					.addContainerGap(81, Short.MAX_VALUE))
		);
		jPanelMain.setLayout(jPanelMainLayout);

		jLayeredPane1.setLayer(jPanelMain, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
		jLayeredPane1Layout.setHorizontalGroup(jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanelMain, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jLayeredPane1Layout.setVerticalGroup(jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanelMain, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jLayeredPane1.setLayout(jLayeredPane1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLayeredPane1));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING));

		pack();
	}// </editor-fold>

	private DefaultTableModel model;

	private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {
		String searchKey = txtSearch.getText();
		TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<DefaultTableModel>(model);
		tblDestinations.setRowSorter(tableRowSorter);
		tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
	}

	/**
	 * @param args the command line arguments
	 */

	public void fillTable(IDestinationService destinationService) {
		model = (DefaultTableModel) tblDestinations.getModel();
		model.setRowCount(0);
		for (Destinations destination : destinationService.getAll()) {
			Object[] row = { destination.getName(), destination.getCity(), destination.getCountry() };
			model.addRow(row);
		}
	}

	public void setManager(IDestinationService destinationService) {
		this.destinationService = destinationService;
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnDelete;
	private javax.swing.JButton btnDetails;
	private javax.swing.JButton jButton1;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPanel jPanelMain;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblSearch;
	private javax.swing.JTable tblDestinations;
	private javax.swing.JTextField txtSearch;
}
